### ISSUE TITLE
Call to undefined method Mews\Captcha\Captcha::renderJs()

### ISSUE THREAD

**Issue by jbuitt** [AbanoubNassem/filament-grecaptcha-field#12]
Hello!

I'm very excited to use your plugin, however I'm hoping you might be able to help me with an issue I'm having. I followed the directions to implement GRecaptcha in my Filament dashboard, but when I attempt to load a page with the field, I get the error:

"Call to undefined method Mews\Captcha\Captcha::renderJs()"

I dug into the code for the \Mews\Captcha\Captcha class and in fact did not see the static method "renderJs" in the class. I did however see the method in the Anhskohbo\NoCaptcha\NoCaptcha class.  

Please let me know if I can provide any files on my system for troubleshooting.

Versions:
Laravel: 11.14.0  
PHP: 8.3.9  
Filament: v3.2.71 
Livewire: v3.5.2

From my composer.json:
abanoubnassem/filament-grecaptcha-field: "^0.0.7",
mews/captcha: "^3.3"
anhskohbo/no-captcha: "^3.4",

Thanks!

**Comment by AbanoubNassem** [comment]
please remove `mews/captcha: "^3.3"`  as it conflicts with `anhskohbo/no-captcha` , and it should work fine.

**Comment by jbuitt** [comment]
Great! That worked. Thanks so much!!
