### ISSUE TITLE
reCaptcha becomes accepted after expiration.

### ISSUE THREAD

**Issue by atenadadkhah** [AbanoubNassem/filament-grecaptcha-field#6]
I noticed that when reCaptcha expires after 1 minute, it accepts the previous one instead of wanting the user to check it again,  and the user can login. Although reCaptcha is saying that it is expired.

**Comment by AbanoubNassem** [comment]
I think this issue could be, related to the plugin I relay on for the captcha : https://github.com/anhskohbo/no-captcha , since my plugin only forward the form value to the `no-captcha` plugin for validation .
